### PR TITLE
Add libc6:armhf to post-install for ARM64 systems

### PR DESCRIPTION
**Pull request by WheezyE**
For https://github.com/ptitSeb/box86/issues/682

### CODE REVIEW

**Comment by WheezyE** [comment]
I wasn't able to test this addition on my own system (I keep getting `not today :(` when I run), but I wanted to propose adding an installation for libc6:armhf to the post-install for aarch64.

This is the error I'm getting when trying to run the script in case it's interesting. I have a GPG key.
```
script is being run from correct directory ✔︎
arch is armhf/armv7l ✔︎
checkinstall is installed ✔︎
cmake is installed ✔︎
'/home/pi/Documents/box86-auto-build' exists ✔︎
script is executable ✔︎
not today :(
```

**Comment by WheezyE** [comment]
I also wanted to say that I have been able to build box86 on aarch64 RPi4B too (using the `-DRPI4ARM64=1` flag) and the resulting binary is armhf and works on RPi4B RPiOS 32&64-bit & RPi3B+ RPiOS 32&64-bit.  Example [here](https://github.com/WheezyE/Winelink/blob/57d1e11d1d2594d7a860bb30cf1b4cb2e8bb3a76/install_winelink.sh#L72).

The `-DRPI4ARM64=1` (or `-DRPI4=1`) build flag works for building on RPi4B & on RPi3B+, but `-DRPI3ARM64=1` (or `-DRPI3=1`) don't work. on the RPi3B+.

**Comment by Itai-Nelken** [comment]
> [...] (I keep getting `not today :(` when I run) [...]
> 
Honestly those scripts are a big mess.
You need to run the `run-once*box86*.sh` (I don't remember the full name).

**Comment by Itai-Nelken** [comment]
@WheezyE any updates?

**Comment by WheezyE** [comment]
Oh this kind of dropped off my radar. I think I ended up finding another
solution for my needs and this can be closed at this time

**Pull request closed without merging**
